version: "3.0"
services:
  app:
    hostname: details-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
    networks:
      - details

networks:
  details:
    name: details
    driver: bridge